name: Build‑Android (Pocket‑Digger)

on:
  push:
    branches: [prototype, main]
  workflow_dispatch:

jobs:
  buildForAndroidPlatform:
    name: Build For Android Platform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-Android

      - uses: game-ci/unity-builder@v4
        with:
          targetPlatform: Android
          unityVersion: 2021.3.21f1
          buildsPath: build
          buildName: PocketDigger
          androidAppBundle: false
          androidKeystoreName: ""
          androidKeystoreBase64: ""
          androidKeystorePass: ""
          androidKeyaliasName: ""
          androidKeyaliasPass: ""
          androidTargetSdkVersion: AndroidApiLevelAuto
          androidExportType: androidPackage
          buildMethod: ""

      - uses: actions/upload-artifact@v4
        with:
          name: Build-Android
          path: build/Android